'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        dashboard: 'Dashboard',
        profile: 'Profile',
        verify: 'Verify Data',
        courses: 'Courses',
        curriculum_management: 'Curriculum Management',
        major_management: 'Major Management',
        competency_management: 'Competency Management',
        activity_management: 'Activity Management',
        templates: 'Templates',
        template_assignments: 'Template Assignments',
        users: 'Users',
        settings: 'Settings',
        logout: 'Logout',
        theme: 'Theme',
        language: 'Language',
        light: 'Light',
        dark: 'Dark',
        search: 'Search...',
        competency_growth: 'Competency Growth',
        competency_chart: 'Competency Chart',
        chart_title: 'Competency Radar Chart',
        filter_year: 'Filter by Year',
        filter_range: 'Filter by Date Range',
        activity_history: 'Activity History',
        course_history: 'Course History',
        verified: 'Verified',
        pending: 'Pending',
        score: 'Score',
        date: 'Date',
        type: 'Type',
        activities: 'Activities',
        courses: 'Courses',
        average_competency: 'Average Competency',
        growth_rate: 'Growth Rate',
        passed_criteria: 'Passed Criteria',
        total_competencies: 'Total Competencies',
        gap_analysis: 'Gap Analysis',
        gap_chart_title: 'Gap Analysis Chart',
        loading: 'Loading...',
        error_loading: 'Error loading data',
        requirement: 'Requirement',
        requirement_criteria: 'Requirement Criteria',
        select_competency: 'Select Competency',
        select_category_label: 'Select Category',
        select_year: 'Select Year',
        year: 'Year',
        click_for_details: '(Click for details)',
        filter: 'Filters',
        select_competency_label: 'Select Competency',
        filter_mode: 'Filter Mode',
        compare_years: 'Compare Years',
        date_range_mode: 'Date Range',
        academic_year: 'Academic Year (multi-select)',
        start_range: 'Start Range',
        end_range: 'End Range',
        show_requirement: 'Show Requirement',
        compared_to_requirement: 'Compared to requirement',
        target: 'Target',
        avg_score: 'Average Score',
        growth: 'Growth',
        no_activities_this_year: 'No activities in this year',
        no_course_history: 'No course history',
        scored_activities: 'Scored Activities',
        available_activities: 'Available Activities',
        competency: 'Competency',
        // Competencies
        tst_comm: 'Communication',
        tst_ct: 'Critical Thinking',
        tst_team: 'Teamwork',
        tst_lead: 'Leadership',
        tst_ethic: 'Ethics',
        tst_digi: 'Digital Literacy',
        // Months
        jan: 'January',
        feb: 'February',
        mar: 'March',
        apr: 'April',
        may: 'May',
        jun: 'June',
        jul: 'July',
        aug: 'August',
        sep: 'September',
        oct: 'October',
        nov: 'November',
        dec: 'December',
        jan_short: 'Jan',
        feb_short: 'Feb',
        mar_short: 'Mar',
        apr_short: 'Apr',
        may_short: 'May',
        jun_short: 'Jun',
        jul_short: 'Jul',
        aug_short: 'Aug',
        sep_short: 'Sep',
        oct_short: 'Oct',
        nov_short: 'Nov',
        dec_short: 'Dec',
        // Login
        login_title: 'KKU Competency System',
        login_subtitle: 'Sign in to access the competency',
        login_email: 'Email',
        login_password: 'Password',
        login_signin: 'Sign In',
        login_signing_in: 'Signing in…',
        login_or: 'or',
        login_sso: 'Sign In with KKU Email',
        login_error: 'Unable to login.',
        structure_guide_title: 'Build the curriculum structure',
        structure_guide_description: 'Complete these steps to continue.',
        structure_guide_add_root: 'Add a main category',
        structure_guide_add_root_hint: 'Start with a main category, such as General Education.',
        structure_guide_select_leaf: 'Select a leaf category',
        structure_guide_select_leaf_hint: 'Choose a category without subcategories to add courses.',
        structure_guide_add_course: 'Add a course',
        structure_guide_add_course_hint: 'Add at least one course to the selected leaf category.',
        structure_guide_complete: 'Complete',
        structure_guide_pending: 'Not complete',
        structure_guide_constraints: 'Structure rules',
        structure_guide_max_depth: 'Categories can be nested up to 4 levels.',
        structure_guide_leaf_only: 'Courses can be placed only in leaf categories.',
        structure_add_root: 'Main category',
        structure_add_child: 'Subcategory',
        structure_add_child_disabled: 'This category is already at the maximum depth of 4 levels.',
        structure_add_course_disabled: 'Select a leaf category to add courses.',
        structure_empty: 'Add a main category to begin.',
        course_actions: 'Course actions',
        edit_course: 'Edit course',
        delete_course: 'Delete course',
        template_create_title: 'Create Template',
        template_step_curriculum: 'Curriculum details',
        template_step_competency: 'Select competency',
        template_cancel: 'Cancel',
        template_back: 'Back',
        template_next: 'Next',
        template_create_action: 'Create Template',
        template_competency_picker_hint: 'Choose the competencies to map to courses in this curriculum. You can select more than one.',
        template_competency_search: 'Search by competency code or name...',
        template_reload_competencies: 'Reload',
        template_manage_competencies: 'Manage competencies',
        template_selected_competencies: 'Selected',
        template_remove_selected_competency: 'Remove selected competency',
        template_competencies_load_failed: 'Unable to load competencies. Your current selections are still available.',
        template_retry: 'Try again',
        template_competency_empty: 'No competencies match your search.',
        template_competency_required: 'Select at least one competency.',
        curriculum_detail_tab_structure: 'Curriculum structure',
        curriculum_detail_tab_metadata: 'Curriculum details',
        curriculum_metadata_title: 'Curriculum details',
        curriculum_metadata_description: 'Core information and the major connected to this curriculum.',
        curriculum_edit_metadata: 'Edit details',
        curriculum_cancel: 'Cancel',
        curriculum_save: 'Save',
        curriculum_code: 'Curriculum code',
        curriculum_academic_year: 'Academic year',
        curriculum_name_th: 'Curriculum name (Thai)',
        curriculum_name_en: 'Curriculum name (English)',
        curriculum_faculty: 'Faculty',
        curriculum_major: 'Major',
        curriculum_degree_level: 'Degree level',
        curriculum_manage_major: 'Manage major information',
        curriculum_go_to_major_management: 'Go to Major Management',
        curriculum_select_faculty: 'Select faculty',
        curriculum_faculty_scope_hint: 'Set by your user permission.',
        curriculum_select_major: 'Select major',
        curriculum_inactive: 'Inactive',
        curriculum_major_draft_only: 'The major can only be changed while this curriculum is a draft.',
        curriculum_degree_managed_in_major: 'Managed from Major Management.',
        curriculum_degree_bachelor: 'Bachelor\'s degree',
        curriculum_degree_master: 'Master\'s degree',
        curriculum_degree_phd: 'Doctoral degree',
        curriculum_degree_other: 'Other',
        curriculum_structure_overview: 'Structure overview',
        curriculum_total_courses: 'Total courses',
        curriculum_total_categories: 'Total categories',
        curriculum_total_credits: 'Total credits',
        curriculum_courses_unit: 'courses',
        curriculum_categories_unit: 'categories',
        curriculum_credits_unit: 'credits',
        curriculum_templates_connected: 'Connected templates',
        curriculum_active_templates: 'Active templates',
        curriculum_items: 'items',
        curriculum_structure_locked_by_active_templates: 'The structure is locked while active templates are connected.',
        curriculum_manage_structure: 'Manage curriculum structure',
    },
    th: {
        dashboard: 'แดชบอร์ด',
        profile: 'ประวัติส่วนตัว',
        verify: 'ตรวจสอบข้อมูล',
        courses: 'หลักสูตร',
        curriculum_management: 'จัดการหลักสูตร',
        major_management: 'จัดการสาขา',
        competency_management: 'จัดการสมรรถนะ',
        activity_management: 'จัดการกิจกรรม',
        templates: 'Templates',
        template_assignments: 'เชื่อม Template กับรุ่น',
        users: 'ผู้ใช้',
        settings: 'การตั้งค่า',
        logout: 'ออกจากระบบ',
        theme: 'ธีม',
        language: 'ภาษา',
        light: 'โหมดสว่าง',
        dark: 'โหมดมืด',
        search: 'ค้นหา...',
        competency_growth: 'การเติบโตของสมรรถนะ',
        competency_chart: 'กราฟสมรรถนะ',
        chart_title: 'แผนภูมิเรดาร์สมรรถนะ',
        filter_year: 'กรองตามปี',
        filter_range: 'กรองตามช่วงเวลา',
        activity_history: 'ประวัติกิจกรรม',
        course_history: 'ประวัติการลงทะเบียนเรียน',
        verified: 'ยืนยันแล้ว',
        pending: 'รอตรวจสอบ',
        score: 'คะแนน',
        date: 'วันที่',
        type: 'ประเภท',
        activities: 'กิจกรรม',
        course: 'หลักสูตร',
        average_competency: 'สมรรถนะเฉลี่ย',
        growth_rate: 'อัตราการเติบโต',
        passed_criteria: 'ผ่านเกณฑ์',
        total_competencies: 'สมรรถนะทั้งหมด',
        gap_analysis: 'การวิเคราะห์ช่องว่าง',
        gap_chart_title: 'แผนภูมิวิเคราะห์ช่องว่าง',
        loading: 'กำลังโหลด...',
        error_loading: 'โหลดข้อมูลไม่สำเร็จ',
        requirement: 'เกณฑ์ที่กำหนด',
        requirement_criteria: 'เกณฑ์หลักสูตร',
        select_competency: 'เลือกสมรรถนะ',
        select_category_label: 'เลือกหมวดหมู่',
        select_year: 'เลือกปี',
        year: 'ปี',
        click_for_details: '(คลิกเพื่อดูรายละเอียด)',
        filter: 'ตัวกรอง',
        select_competency_label: 'เลือกสมรรถนะ',
        select_category_label: 'เลือกหมวดหมู่',
        courses: 'หลักสูตร',
        filter_mode: 'โหมดการกรอง',
        compare_years: 'เปรียบเทียบปี',
        date_range_mode: 'ช่วงเวลา',
        academic_year: 'ปีการศึกษา (เลือกได้หลายปี)',
        start_range: 'ช่วงเวลาเริ่มต้น',
        end_range: 'ช่วงเวลาสิ้นสุด',
        show_requirement: 'แสดงเกณฑ์หลักสูตร',
        compared_to_requirement: 'เทียบกับเกณฑ์หลักสูตร',
        target: 'เป้าหมาย',
        avg_score: 'คะแนนเฉลี่ย',
        growth: 'การเติบโต',
        no_activities_this_year: 'ไม่มีกิจกรรมในปีนี้',
        no_course_history: 'ไม่มีประวัติการลงทะเบียนเรียน',
        scored_activities: 'กิจกรรมที่ได้รับคะแนนแล้ว',
        available_activities: 'กิจกรรมที่สามารถทำได้',
        competency: 'สมรรถนะ',
        // Competencies (fallback if api doesn't provide)
        tst_comm: 'การสื่อสาร',
        tst_ct: 'การคิดเชิงวิพากษ์',
        tst_team: 'การทำงานเป็นทีม',
        tst_lead: 'ความเป็นผู้นำ',
        tst_ethic: 'จริยธรรม',
        tst_digi: 'ความรอบรู้ทางดิจิทัล',
        // Months
        jan: 'มกราคม',
        feb: 'กุมภาพันธ์',
        mar: 'มีนาคม',
        apr: 'เมษายน',
        may: 'พฤษภาคม',
        jun: 'มิถุนายน',
        jul: 'กรกฎาคม',
        aug: 'สิงหาคม',
        sep: 'กันยายน',
        oct: 'ตุลาคม',
        nov: 'พฤศจิกายน',
        dec: 'ธันวาคม',
        jan_short: 'ม.ค.',
        feb_short: 'ก.พ.',
        mar_short: 'มี.ค.',
        apr_short: 'เม.ย.',
        may_short: 'พ.ค.',
        jun_short: 'มิ.ย.',
        jul_short: 'ก.ค.',
        aug_short: 'ส.ค.',
        sep_short: 'ก.ย.',
        oct_short: 'ต.ค.',
        nov_short: 'พ.ย.',
        dec_short: 'ธ.ค.',
        // Login
        login_title: 'ระบบ Competency',
        login_subtitle: 'ลงชื่อเข้าใช้ระบบ Competency',
        login_email: 'อีเมล',
        login_password: 'รหัสผ่าน',
        login_signin: 'เข้าสู่ระบบ',
        login_signing_in: 'กำลังเข้าสู่ระบบ…',
        login_or: 'หรือ',
        login_sso: 'เข้าสู่ระบบด้วย SSO',
        login_error: 'ไม่สามารถเข้าสู่ระบบได้',
        structure_guide_title: 'จัดโครงสร้างหลักสูตร',
        structure_guide_description: 'ทำรายการต่อไปนี้ให้ครบเพื่อไปขั้นถัดไป',
        structure_guide_add_root: 'เพิ่มหมวดวิชาหลัก',
        structure_guide_add_root_hint: 'เริ่มจากหมวดหลัก เช่น หมวดศึกษาทั่วไป',
        structure_guide_select_leaf: 'เลือกหมวดปลายทาง',
        structure_guide_select_leaf_hint: 'เลือกหมวดที่ไม่มีหมวดย่อยเพื่อเพิ่มรายวิชา',
        structure_guide_add_course: 'เพิ่มรายวิชา',
        structure_guide_add_course_hint: 'เพิ่มอย่างน้อย 1 รายวิชาในหมวดปลายทางที่เลือก',
        structure_guide_complete: 'สำเร็จ',
        structure_guide_pending: 'ยังไม่เสร็จ',
        structure_guide_constraints: 'ข้อจำกัดโครงสร้าง',
        structure_guide_max_depth: 'สร้างหมวดวิชาได้สูงสุด 4 ระดับ',
        structure_guide_leaf_only: 'เพิ่มรายวิชาได้เฉพาะหมวดปลายทาง',
        structure_add_root: 'หมวดหลัก',
        structure_add_child: 'หมวดย่อย',
        structure_add_child_disabled: 'หมวดนี้อยู่ระดับสูงสุด 4 ระดับแล้ว',
        structure_add_course_disabled: 'เลือกหมวดปลายทางเพื่อเพิ่มรายวิชา',
        structure_empty: 'เพิ่มหมวดหลักเพื่อเริ่มต้น',
        course_actions: 'จัดการรายวิชา',
        edit_course: 'แก้ไขรายวิชา',
        delete_course: 'ลบรายวิชา',
        template_create_title: 'สร้าง Template ใหม่',
        template_step_curriculum: 'ข้อมูลหลักสูตร',
        template_step_competency: 'เลือก Competency',
        template_cancel: 'ยกเลิก',
        template_back: 'ย้อนกลับ',
        template_next: 'ถัดไป',
        template_create_action: 'สร้าง Template',
        template_competency_picker_hint: 'เลือก Competency ที่ต้องการผูกกับรายวิชาในหลักสูตรนี้ (เลือกได้หลายตัว)',
        template_competency_search: 'ค้นหารหัสหรือชื่อสมรรถนะ...',
        template_reload_competencies: 'โหลดใหม่',
        template_manage_competencies: 'จัดการสมรรถนะ',
        template_selected_competencies: 'เลือกแล้ว',
        template_remove_selected_competency: 'นำสมรรถนะที่เลือกออก',
        template_competencies_load_failed: 'ไม่สามารถโหลดรายการสมรรถนะได้ โดยรายการที่เลือกไว้ยังคงอยู่',
        template_retry: 'ลองใหม่',
        template_competency_empty: 'ไม่พบ Competency ที่ตรงกับการค้นหา',
        template_competency_required: 'กรุณาเลือก Competency อย่างน้อย 1 ตัว',
        curriculum_detail_tab_structure: 'โครงสร้างหลักสูตร',
        curriculum_detail_tab_metadata: 'ข้อมูลหลักสูตร',
        curriculum_metadata_title: 'ข้อมูลหลักสูตร',
        curriculum_metadata_description: 'ข้อมูลพื้นฐานและสาขาที่เชื่อมกับหลักสูตรนี้',
        curriculum_edit_metadata: 'แก้ไขข้อมูล',
        curriculum_cancel: 'ยกเลิก',
        curriculum_save: 'บันทึก',
        curriculum_code: 'รหัสหลักสูตร',
        curriculum_academic_year: 'ปีการศึกษา',
        curriculum_name_th: 'ชื่อหลักสูตร (ภาษาไทย)',
        curriculum_name_en: 'ชื่อหลักสูตร (ภาษาอังกฤษ)',
        curriculum_faculty: 'คณะ',
        curriculum_major: 'สาขา',
        curriculum_degree_level: 'ระดับปริญญา',
        curriculum_manage_major: 'จัดการข้อมูลสาขา',
        curriculum_go_to_major_management: 'ไปหน้าจัดการสาขา',
        curriculum_select_faculty: 'เลือกคณะ',
        curriculum_faculty_scope_hint: 'กำหนดตามสิทธิ์ผู้ใช้งาน',
        curriculum_select_major: 'เลือกสาขา',
        curriculum_inactive: 'ปิดใช้งาน',
        curriculum_major_draft_only: 'เปลี่ยนสาขาได้เฉพาะหลักสูตร Draft',
        curriculum_degree_managed_in_major: 'จัดการจากหน้าสาขา',
        curriculum_degree_bachelor: 'ปริญญาตรี',
        curriculum_degree_master: 'ปริญญาโท',
        curriculum_degree_phd: 'ปริญญาเอก',
        curriculum_degree_other: 'อื่น ๆ',
        curriculum_structure_overview: 'ภาพรวมโครงสร้าง',
        curriculum_total_courses: 'รายวิชาทั้งหมด',
        curriculum_total_categories: 'หมวดวิชาทั้งหมด',
        curriculum_total_credits: 'หน่วยกิตรวม',
        curriculum_courses_unit: 'วิชา',
        curriculum_categories_unit: 'หมวด',
        curriculum_credits_unit: 'หน่วยกิต',
        curriculum_templates_connected: 'Template ที่เชื่อม',
        curriculum_active_templates: 'Active Template',
        curriculum_items: 'รายการ',
        curriculum_structure_locked_by_active_templates: 'โครงสร้างหลักสูตรถูกล็อก เพราะมี Active Template เชื่อมอยู่',
        curriculum_manage_structure: 'จัดการโครงสร้างหลักสูตร',
    }
};

translations.en.student_management = 'Student Management';
translations.th.student_management = 'จัดการข้อมูลนักศึกษา';

export function LanguageProvider({ children }) {
    // Always start with 'th' to match server render and avoid hydration mismatch
    const [language, setLanguage] = useState('th');

    // Sync from localStorage after hydration
    useEffect(() => {
        const saved = localStorage.getItem('language');
        if (saved && saved !== language) {
            setLanguage(saved);
        }
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key) => {
        return translations[language]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
